name: ItemUtility
main: kr.skylightqp.itemutility.ItemUtility
version: 2.0

commands:
  iu:
    description: ItemUtility admin command.
    permission: itemutility.*
    permission-message: §6§l[ItemUtility] §c당신은 권한을 갖고있지 않습니다!